---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBi96CeAKJJtDRIbhIgGZJGneXE+CBws3v4hoq5Z2LbzVlfc3LPiN/QET1rq+erDCRucyduw+bgH5Mks6t1Ejks8UV+ce8qBa8AnvNGkctUaLh5aJZNU8n3h8ZMqenwPXr6KHTPygAEIxarUB5EGkjAXyrtewEGH+8/216FXorduOErWVOnEj6NKlJfDnv+csQ/Fy/QLHhLWZorNwJWVJoyvzFDz2rt42Y7kz6aXeJZsrVMVOzuC6C8yV+KP4KDPBCoDKw8CiEw14DjoTXwSclhkOJGNCOTdfjCXjGrkZW0/DnKFbg8NQDG8OUHM2h2SBGFLNfZT6oSUCDoca4lq0EnkSpHYVQmwMUMapQYasJXQfLOLcnvPim8LQ2vPLnH7SD9peZsR6gIwAAOEKIWxWZYoRQadzV32fvrMLoQnItrEHjTfYT3bC2caBtNDFp7xoy5ysI9qm4IS/Nt1qFLkJ0hyZcEyR3RCfadT4OgTj/M2cLhPpoYOSgWX0Qit7DzXGfacEOelrYtbOFtdQ3M5dqDviAliPZk4kL8WY/phUvyAJb7WiTH7vqtarG9dk59uDzZIBgZNt3SRBXfUu2en0E551nw33Jk/dD/ucUqH3YQgJ2JN73ebj8lTWV9XsWoIy71SJReWDbPIgqzH2L41r7Rdw4g1VDQl1pTiYyHyC4BuWv+PgP112KYf7GYPJsR+SAPIUFL4dSVfYJbkxIcaVeP/75m3cFSrgeAJGve093lYpI/0QpKxcLQiVZMXMPyk2y5jKs=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
